/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;
import DbOject.Author;
import Lib.lib;
import com.db4o.Db4oEmbedded;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import com.db4o.query.Predicate;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Calendar;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author chienktv90
 */
public class frmAuthor extends javax.swing.JFrame {
    public ObjectContainer db;
    public DefaultTableModel tbmodel;
    boolean luu;
    public Author auUpdate;
    /**
     * Creates new form frmAuthor
     */
    public frmAuthor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbAuthor = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txttacgia = new javax.swing.JTextField();
        lbSoA2 = new javax.swing.JLabel();
        lbSoB2 = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jtbAuthor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TenTacGia", "Birthday"
            }
        ));
        jtbAuthor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbAuthorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtbAuthorMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jtbAuthor);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng thao tác"));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnClose.setText("Thoát");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnExport.setText("Export");
        btnExport.setToolTipText("");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHuy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLuu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExport))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnHuy)
                    .addComponent(btnClose)
                    .addComponent(btnLuu)
                    .addComponent(btnExport)))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin chi tiết"));

        lbSoA2.setText("Tên tác giả");

        lbSoB2.setText("Ngày sinh");

        txtNgaySinh.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSoA2)
                    .addComponent(lbSoB2))
                .addGap(61, 61, 61)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txttacgia, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(txtNgaySinh)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttacgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSoA2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSoB2)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        db = Db4oEmbedded.openFile("F:/db4oExample.db4o");
        LoadAllData();
    }//GEN-LAST:event_formWindowOpened

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        setcontrols(true);
        luu = true;
        setresets();
        txttacgia.requestFocus();
    }//GEN-LAST:event_btnThemActionPerformed

    private void jtbAuthorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbAuthorMouseEntered
        // TODO add your handling code here:
        //txtmalop.setEnabled(false);
        
    }//GEN-LAST:event_jtbAuthorMouseEntered

    private void jtbAuthorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbAuthorMouseClicked
        // TODO add your handling code here:
        txttacgia.setText(jtbAuthor.getValueAt(jtbAuthor.getSelectedRow(), 0).toString());
        //txtNgaySinh.setText(jtbAuthor.getValueAt(jtbAuthor.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_jtbAuthorMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        luu = false;
        setcontrols(true);
        txttacgia.requestFocus();
        auUpdate = (Author) db.queryByExample(new Author(txttacgia.getText())).next(); // tim "txttacgia.getText()" trong data, lay dong hien tai
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        tbmodel.getDataVector().removeAllElements();
        LoadAllData();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        //setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int xoa = JOptionPane.showConfirmDialog(null, "delete "+txttacgia.getText(),"Xoa", JOptionPane.YES_NO_OPTION);
        if (xoa == JOptionPane.OK_OPTION)
        {
            try
            {
                Author au = (Author)db.queryByExample(new Author(txttacgia.getText())).next();
                db.delete(au);
                tbmodel.getDataVector().removeAllElements();
                LoadAllData();
            }
            catch (Exception ex)
            {
                JOptionPane.showMessageDialog(this, "Xoa khong thanh cong, Error:"+ex);
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        //Buoc 3.1 Them
        if (luu)
        {
            try
            {
                if ((txttacgia.getText().length() > 255) || (txttacgia.getText().length()<1) )
                {
                    JOptionPane.showMessageDialog(this, "Kiểm tra\nSo luong ky tu nhap");
                    return;
                }
                //---------------------------kết thúc test lỗi
                else
                {
                    String tenTacGia  = txttacgia.getText();
                    //String tenlop=txttenlop.getText();
                    Author TG = new Author(tenTacGia);
                    db.store(TG);
                    JOptionPane.showMessageDialog(this,"Them "+txttacgia.getText());
                    tbmodel.getDataVector().removeAllElements();
                    LoadAllData();
                    jtbAuthor.setRowSelectionInterval(jtbAuthor.getRowCount()-1, jtbAuthor.getRowCount()-1);
                }
            }
            catch (Exception ex)
            {
                JOptionPane.showMessageDialog(this, "Them khong thanh cong, Error:"+ex);
            }
        }
        //Buoc 4.1 Sua
        else if (!luu)
        {
            try
            {
                //kiểm tra độ dài ký tự nhập va khoang trang
                if ((txttacgia.getText().length() > 255) || (txttacgia.getText().length()<1) )
                {
                    JOptionPane.showMessageDialog(this, "Kiểm tra\nSo luong ky tu nhap");
                    return;
                }
                //---------------------------kết thúc test lỗi
                else
                {                  
                    int index= jtbAuthor.getSelectedRow();  
                    String tenTacGia  = txttacgia.getText();
                    //Author au = (Author) db.queryByExample(new Author(tenTacGia)).next(); // tim trong data co dong tenTacGia
                    
                    Calendar calendar = Calendar.getInstance(); 
                    calendar.set(1990, Calendar.OCTOBER, 10); 
                    
                    auUpdate.setBirthday(calendar.getTime()); 
                    auUpdate.setName(tenTacGia);
                    db.store(auUpdate);
                    
                    tbmodel.getDataVector().removeAllElements();
                    LoadAllData();
                    jtbAuthor.setRowSelectionInterval(index, index);
                    JOptionPane.showMessageDialog(this,"Da cap nhat "+txttacgia.getText());
                }
            }
            catch (Exception ex)
            {
                JOptionPane.showMessageDialog(this, "Cap nhat khong thanh cong, Error:"+ex);
            }
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        int option = fc.showSaveDialog(this);
        if(option == JFileChooser.APPROVE_OPTION){
            String filename = fc.getSelectedFile().getName(); 
            String path = fc.getSelectedFile().getParentFile().getPath();
            int len = filename.length();
            String ext = "";
            String file = "";
            if(len > 4){
                    ext = filename.substring(len-4, len);
            }
            if(ext.equals(".xls")){
                    file = path + "\\" + filename; 
            }else{
                    file = path + "\\" + filename + ".xls"; 
            }
            lib uselib = new lib();
            uselib.toExcel(jtbAuthor, new File(file));
        }
    }//GEN-LAST:event_btnExportActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAuthor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAuthor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAuthor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAuthor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAuthor().setVisible(true);
            }
        });
    }
    
    
    public void LoadAllData()
    {   
        setcontrols(false);
        setresets();
        Author au =new Author(); // tim tat ca	
        ObjectSet<Author> Aus = db.queryByExample(au);
	for (Author a:Aus) 
	{
            Object[] row={a.getName(), a.getBirthday()};
            tbmodel = (DefaultTableModel) jtbAuthor.getModel();
            tbmodel.addRow(row);  
	}
        jtbAuthor.setRowSelectionInterval(0, 0);
        txttacgia.setText(jtbAuthor.getValueAt(jtbAuthor.getSelectedRow(), 0).toString());
    }
    
    public void setcontrols(boolean an)
    {
        btnHuy.setEnabled(an);
        btnLuu.setEnabled(an);
        btnThem.setEnabled(!an);
        btnSua.setEnabled(!an);
        btnXoa.setEnabled(!an);
        txttacgia.setEnabled(an);        
        jtbAuthor.setEnabled(!an);
    }
    
    //làm trắng controls
    public void setresets()
    {
        txttacgia.setText(null);
        txtNgaySinh.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbAuthor;
    private javax.swing.JLabel lbSoA2;
    private javax.swing.JLabel lbSoB2;
    private javax.swing.JFormattedTextField txtNgaySinh;
    private javax.swing.JTextField txttacgia;
    // End of variables declaration//GEN-END:variables
}
