/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import DbOject.Buucuc;
import Lib.lib;
import com.db4o.Db4oEmbedded;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import java.io.File;
import java.util.Calendar;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chienktv90
 */
public class frmBuucuc extends javax.swing.JFrame {
    public ObjectContainer db;
    public DefaultTableModel tbmodel;
    boolean luu;
    public Buucuc bcUpdate;

    /**
     * Creates new form frmBuucuc
     */
    public frmBuucuc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtMaBuuCuc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTenBuuCuc = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbBuuCuc = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin"));

        jLabel1.setText("Mã bưu cục");

        jLabel3.setText("Tên bưu cục");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(13, 13, 13)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTenBuuCuc, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(txtMaBuuCuc))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaBuuCuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenBuuCuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnClose.setText("Thoát");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnExport.setText("Export");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHuy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLuu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExport)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnLuu)
                    .addComponent(btnXoa)
                    .addComponent(btnSua)
                    .addComponent(btnHuy)
                    .addComponent(btnClose)
                    .addComponent(btnExport))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jtbBuuCuc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Bưu Cục", "Tên Bưu Cục"
            }
        ));
        jtbBuuCuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbBuuCucMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbBuuCuc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        //Buoc 3.1 Them
        if (luu)
        {
            try
            {
                if ((txtMaBuuCuc.getText().length() > 10) || (txtMaBuuCuc.getText().length()<1) )
                {
                    JOptionPane.showMessageDialog(this, "Kiểm tra\nSo luong ky tu nhap");
                    return;
                }
                else if ((txtTenBuuCuc.getText().length() > 10) || (txtTenBuuCuc.getText().length()<1) )
                {
                    JOptionPane.showMessageDialog(this, "Kiểm tra\nSo luong ky tu nhap");
                    return;
                }
                //---------------------------kết thúc test lỗi
                else
                {
                    String maBuuCuc  = txtMaBuuCuc.getText();
                    String tenBuuCuc = txtTenBuuCuc.getText();
                    String diachi="";
                    Buucuc bc = new Buucuc(maBuuCuc, tenBuuCuc, diachi);
                    
                    db.store(bc);

                    JOptionPane.showMessageDialog(this,"Them "+txtTenBuuCuc.getText());
                    tbmodel.getDataVector().removeAllElements();
                    LoadAllData();
                    jtbBuuCuc.setRowSelectionInterval(jtbBuuCuc.getRowCount()-1, jtbBuuCuc.getRowCount()-1);
                }
            }
            catch (Exception ex)
            {
                JOptionPane.showMessageDialog(this, "Them khong thanh cong, Error:"+ex);
            }
        }
        //Buoc 4.1 Sua
        else if (!luu)
        {
            
            try
            {
                if ((txtMaBuuCuc.getText().length() > 10) || (txtMaBuuCuc.getText().length()<1) )
                {
                    JOptionPane.showMessageDialog(this, "Kiểm tra\nSo luong ky tu nhap");
                    return;
                }
                else if ((txtTenBuuCuc.getText().length() > 10) || (txtTenBuuCuc.getText().length()<1) )
                {
                    JOptionPane.showMessageDialog(this, "Kiểm tra\nSo luong ky tu nhap");
                    return;
                }
                //---------------------------kết thúc test lỗi
                else
                {                  
                    int index= jtbBuuCuc.getSelectedRow(); 
                    String maBuuCuc  = txtMaBuuCuc.getText();
                    String tenBuuCuc = txtTenBuuCuc.getText();
                    //Author au = (Author) db.queryByExample(new Author(tenTacGia)).next(); // tim trong data co dong tenTacGia
                    
                    bcUpdate.setIdBuuCuc(maBuuCuc);
                    bcUpdate.setTenBuuCuc(tenBuuCuc);
                    db.store(bcUpdate);
                    
                    tbmodel.getDataVector().removeAllElements();
                    LoadAllData();
                    jtbBuuCuc.setRowSelectionInterval(index, index);
                    JOptionPane.showMessageDialog(this,"Da cap nhat "+tenBuuCuc);
                }
            }
            catch (Exception ex)
            {
                JOptionPane.showMessageDialog(this, "Cap nhat khong thanh cong, Error:"+ex);
            }
            
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        setcontrols(true);
        luu = true;
        setresets();
        txtMaBuuCuc.requestFocus();//
    }//GEN-LAST:event_btnThemActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        db = Db4oEmbedded.openFile("F:/db4oExample.db4o");
        LoadAllData();
    }//GEN-LAST:event_formWindowOpened

    private void jtbBuuCucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbBuuCucMouseClicked
        // TODO add your handling code here:
        txtMaBuuCuc.setText(jtbBuuCuc.getValueAt(jtbBuuCuc.getSelectedRow(), 0).toString());
        txtTenBuuCuc.setText(jtbBuuCuc.getValueAt(jtbBuuCuc.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_jtbBuuCucMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int xoa = JOptionPane.showConfirmDialog(null, "delete "+txtMaBuuCuc.getText(),"Xoa", JOptionPane.YES_NO_OPTION);
        if (xoa == JOptionPane.OK_OPTION)
        {
            try
            {
                Buucuc bc = (Buucuc)db.queryByExample(new Buucuc(txtMaBuuCuc.getText())).next();
                db.delete(bc);
                tbmodel.getDataVector().removeAllElements();
                LoadAllData();
            }
            catch (Exception ex)
            {
                JOptionPane.showMessageDialog(this, "Xoa khong thanh cong, Error:"+ex);
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        luu = false;
        setcontrols(true);
        txtMaBuuCuc.requestFocus();
        bcUpdate = (Buucuc) db.queryByExample(new Buucuc(txtMaBuuCuc.getText())).next();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
       tbmodel.getDataVector().removeAllElements();
       LoadAllData();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        int option = fc.showSaveDialog(this);
        if(option == JFileChooser.APPROVE_OPTION){
            String filename = fc.getSelectedFile().getName(); 
            String path = fc.getSelectedFile().getParentFile().getPath();
            int len = filename.length();
            String ext = "";
            String file = "";
            if(len > 4){
                    ext = filename.substring(len-4, len);
            }
            if(ext.equals(".xls")){
                    file = path + "\\" + filename; 
            }else{
                    file = path + "\\" + filename + ".xls"; 
            }
            lib uselib = new lib();
            uselib.toExcel(jtbBuuCuc, new File(file));
        }
    }//GEN-LAST:event_btnExportActionPerformed
    
    public void LoadAllData()
    {   
        setcontrols(false);
        setresets();
        Buucuc bc =new Buucuc(); // tim tat ca	
        ObjectSet<Buucuc> bcs = db.queryByExample(bc);
	for (Buucuc a:bcs) 
	{
            Object[] row={a.getIdBuuCuc(), a.getTenBuuCuc()};
            tbmodel = (DefaultTableModel) jtbBuuCuc.getModel();
            tbmodel.addRow(row);  
	}
        jtbBuuCuc.setRowSelectionInterval(0, 0);
        txtMaBuuCuc.setText(jtbBuuCuc.getValueAt(jtbBuuCuc.getSelectedRow(), 0).toString());
        txtTenBuuCuc.setText(jtbBuuCuc.getValueAt(jtbBuuCuc.getSelectedRow(), 1).toString());
    }
    
    public void setcontrols(boolean an)
    {
        //btnHuy.setEnabled(an);
        btnLuu.setEnabled(an);
        btnThem.setEnabled(!an);
        //btnSua.setEnabled(!an);
        //btnXoa.setEnabled(!an);
        txtMaBuuCuc.setEnabled(an); 
        txtTenBuuCuc.setEnabled(an);
        jtbBuuCuc.setEnabled(!an);
    }
    
    //làm trắng controls
    public void setresets()
    {
        txtMaBuuCuc.setText("");
        txtTenBuuCuc.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBuucuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBuucuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBuucuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBuucuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBuucuc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbBuuCuc;
    private javax.swing.JTextField txtMaBuuCuc;
    private javax.swing.JTextField txtTenBuuCuc;
    // End of variables declaration//GEN-END:variables
}
